### ISSUE TITLE
Test "041_elementInit.html" triggers infinite Events

### ISSUE THREAD

**Issue by telesma** [pr83/ylc#3]
When I run "041_elementInit.html" in the browser I got infinite console logs "InternalError: too much recursion". 

Thank you for your great work!

**Comment by pr83** [comment]
Hello,
Thank you, I know about it - the purpose of that test was to replicate an issue. I do not aim to really "fix" the issue (it's a bit inevitable), but I originally wanted to at least report what's going on in a user-friendly way.

What's really going on:

There is this span:
<span data-ylcEvents="ylcElementInitialized: doSomething"></span>

The "doSomething" method is executed as soon as Yellow code comes across that SPAN, before it has reached the remaining elements in the view. So esentially in the middle of processing the view. The event handler "doSomething" in the controller then tries to update the model (which would consequently update the view) by calling "context.updateModel". But since it triggers the update while we are in the middle of updating the view for the first time, we get an infinite recursion.

I got this problem on a real-world project and it took me a while to realize why the infinite recursion happened, so I wanted to implement some detection of this kind of problem (but haven't done so yet), hence the test.

**Comment by telesma** [comment]
Thanks a lot for the explanation!
